### PR TITLE
docs: Add Figma TechBites videos

### PR DESCRIPTION
**Pull request by morning4coffe-dev**
Issue: internal 44-47

### CODE REVIEW

**Comment by morning4coffe-dev** [comment]
CC @agneszitte, @carldebilly

**Comment by carldebilly** [comment]
PR are not accepted on this repo because it's overwritten from the private one each time.

**Review by carldebilly — CHANGES_REQUESTED** [review]
PR are not accepted on this repo because it's overwritten from the private one each time.

**Comment by morning4coffe-dev** [comment]
@carldebilly Thanks for pointing that out. I just saw the description of the repo now 🙃 I will move the PR changes to Uno.Figma

**Comment by morning4coffe-dev** [comment]
Closing in favor of https://github.com/unoplatform/Uno.Figma/pull/2506

**Pull request closed without merging**
